version: "3.8"

services:
  stats:
    build:
      context: ./stats
      target: development
    volumes:
      - ./stats:/src
      - /src/node_modules
    command: npm run start:dev
    ports:
      - "8089:8000"
    environment:
      NODE_ENV: development
      DEBUG: src:*
    
